### ISSUE TITLE
Exception when starting Frinika on Win10 JDK17

### ISSUE THREAD

**Issue by jjazzboss** [petersalomonsen/frinika#3]
When asked I selected "Default server". 

$ java -jar frinika.jar
extracting files from lib/amd64/Windows 10/ to C:\cygwin64\tmp:
Using language: français
config: TICKS_PER_QUARTER=128
config: TEXT_LANE_FONT=java.awt.Font[family=Arial,name=Arial,style=plain,size=8]
config: DEFAULT_SOUNDFONT=C:\Users\Jerome\frinika\soundfonts\8MBGMSFX.SF2
config: JACK_AUTO_CONNECT=false
config: GROOVE_PATTERN_DIRECTORY=C:\Users\Jerome\frinika\groovepatterns
config: BIG_ENDIAN=false
config: MULTIPLEXED_AUDIO=false
config: MOUSE_NUMBER_DRAG_INTENSITY=2.0
config: MAXIMIZE_WINDOW=false
config: MIDIIN_DEVICES_LIST=
config: sampleRate=44100
config: PATCHNAME_DIRECTORY=C:\Users\Jerome\frinika\patchname
config: AUDIO_BUFFER_LENGTH=512
config: SETUP_DONE=true
config: AUTOMATIC_CHECK_FOR_NEW_VERSION=true
config: SEQUENCER_PRIORITY=0
config: DIRECT_MONITORING=false
config: SCRIPTS_DIRECTORY=C:\Users\Jerome\frinika\scripts
config: SOUNDFONT_DIRECTORY=C:\Users\Jerome\frinika\soundfonts
config: AUDIO_DIRECTORY=C:\Users\Jerome\frinika\audio
no saved property for configuration option LAST_PROJECT_FILENAME, using default
config: MULTIPLEXED_AUDIO=false
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
        at com.frinika.project.FrinikaAudioSystem.getAudioServerInit(FrinikaAudioSystem.java:173)
        at com.frinika.settings.InitialAudioServerPanel$1.actionPerformed(InitialAudioServerPanel.java:87)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
        at java.desktop/java.awt.Component.show(Component.java:1728)
        at java.desktop/java.awt.Component.setVisible(Component.java:1675)
        at java.desktop/java.awt.Window.setVisible(Window.java:1036)
        at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
        at com.frinika.settings.SetupDialog.showSettingsModal(SetupDialog.java:64)
        at com.frinika.FrinikaMain$1.actionPerformed(FrinikaMain.java:93)
        at com.frinika.WelcomeDialog$1.actionPerformed(WelcomeDialog.java:110)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: uk.org.toot.audio.server.spi.AudioServerServiceProvider is not an ImageIO SPI class
        at java.desktop/javax.imageio.spi.ServiceRegistry.checkClassAllowed(ServiceRegistry.java:716)
        at java.desktop/javax.imageio.spi.ServiceRegistry.lookupProviders(ServiceRegistry.java:170)
        at uk.org.toot.service.Services.lookup(Services.java:20)
        at uk.org.toot.audio.server.AudioServerServices.scan(AudioServerServices.java:63)
        at uk.org.toot.audio.server.AudioServerServices.<clinit>(AudioServerServices.java:23)
        ... 93 more

**Comment by jjazzboss** [comment]
I realized the app is quite old, I switched to JDK8 and it works now 👍 

I'm the developer of JJazzLab, another music app in Java which generates dynamic backing tracks. I just discovered Frinika and I'm impressed by all the work done. I'd like to add a piano-roll editor and a notation window in JJazzLab. JJazzLab is also open-source but LGPL, so I can't directly reuse the GPL code, that's a pity... At least I'll try to get some ideas. Is there somewhere some docs that can help understand the app architecture ?

**Comment by petersalomonsen** [comment]
Hi,

Frinika was at its most active in the years 2006-2010, and maybe you'll find something from the mailing-list discussions here: https://sourceforge.net/p/frinika/mailman/frinika-developers/

Very briefly I can say that the idea has been to stay as close to Javasound standards as possible, using the Javasound plugin-architecture for synths and effects. The built-in sequencer was patched for some timing issues, but otherwise it's the same. The mixer is based on Toot audio, and has several effects built-in. Serializing of song data does not persist raw midi events, but instead notes including their durations, which are grouped in "parts".

Probably the best docs are the videos in this playlist: https://www.youtube.com/watch?v=7-HjFczAAvI&list=PLv5wm4YuO4Iw-lg8K4XKHoUKx--EBnoKr

And there should also be other tutorials by different users around the web.

/Peter

**Comment by jjazzboss** [comment]
thanks
